### PR TITLE
Added typedefs for ZJS APIs

### LINKED ISSUE #193: Feature: add type definition for ZJS APIs in the IDE
**Issue description**
The current IDE type definitions doesn't support any ZJS APIs and the code completion lookup doesn't work for any ZJS APIs.

**Current behavior**
When you type in the editor, it doesn't not automatically look up APIs available for that JS object, but it pops up other JS modules like DOM and Node, which are not supported.

**Expected behavior**
When you type in the editor, it should automatically look up APIs available for that JS object.

### PR DESCRIPTION
**Pull request by jimmy-huang**
Created ZJS API type definition and overwrite default editor options

Fix #193

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by jimmy-huang** [comment]
@siovene, this is a WIP patch and I need some help merging this into the ide.  There are a couple issues remaining:

1. I am trying to provide the type definition as a stand-alone .d.ts file that can be loaded, but without conflicting the other module typings, for example like (./tools/manual_typings/project/sample.package.d.ts), but when I tried to put this in there, and if I build the IDE using npm start, it have errors conflicting with other modules like the built-tin es2015 or some others.  So now I am just overwriting the default compiler options in the editor and loading it from a string.

2. The typedefs do not work well for the require("") module loading mechanism, since the objects derived from require() has no type defined, it's impossible to look them up.  I am trying to follow the guide here https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html, and use the module-function.d.ts template to create a module that can be loaded using require(), but no luck getting it work, so maybe you know a way how to do this properly?  Currently you can see in my patch that I am using a hack to define requireAIO() as a valid function instead of calling require("AIO"), just to test the interfaces.

I also submitted a patch in ZJS, which is a standalone file so that you can also pull from that later when we update APIs.  See https://github.com/01org/zephyr.js/pull/1572

**Comment by siovene** [comment]
Hi @jimmy-huang,
not sure about question 2, but could you try something like this?

https://stackoverflow.com/a/43080286/1203785

**Comment by jimmy-huang** [comment]
@xiaoyu3x can you test this patch to see if the auto-completions works for you?  If you can sanity-check if all the APIs are covered, that would be great.

**Comment by xiaoyu3x** [comment]
hi, @jimmy-huang 
I just verified this PR and glad to see your PR works well.
But there isn't 'gfx' module that is leaded in PR. Is it necessary to import 'gfx'?

**Comment by jimmy-huang** [comment]
@xiaoyu3x, I didn't add gfx, is this actually usable in the ide?  If it is, I can just add it, it's not hard.

**Comment by brianjjones** [comment]
@jimmy-huang  Looks good to me, let me know when you are happy with it and I'll merge it.

**Comment by jimmy-huang** [comment]
@xiaoyu3x please test with the updated changes.

**Comment by xiaoyu3x** [comment]
hello, @jimmy-huang
 
I just verified again and PR worked well.

**Pull request merged**
