### PR TITLE
Adding device functions

### PR DESCRIPTION
**Pull request by brianjjones**
These functions will cover the ones lost by removing the ability
to type in the console. Needed for the upcoming ASHELL changes.

Signed-off-by: Brian Jones <brian.j.jones@intel.com>

### CODE REVIEW

**Comment by zolkis** [comment]
One needs to run `./node_modules/.bin/gulp build.bundle.rxjs` before running `npm start`.

**Comment by zolkis** [comment]
I cloned your repo and checked out the [branch](https://github.com/brianjjones/zephyrjs-ide-1/commits/add_device_func), but I don't know what it is supposed to do. 

First off, it tries to open a WebUSB through UART (interface 2), so it won't connect to a board flashed with the IDE protocol. I copied my version of webusb.port.ts that probes both interfaces (IDE and UART); with that one it connected, but then it didn't work. 

I wonder where can I edit and send commands to the device. The UI looks the same as before.

**Comment by brianjjones** [comment]
@zolkis Sorry I wasn't able to get the command line button in just yet.  But I did revert my previous changes so you should be able to browse / open files on the device using the 'Device' tab. I'll keep working on it tomorrow.

**Comment by xiaoyu3x** [comment]
hi, @brianjjones  
Glad to see that `SidebarDeviceFiles component` has been fixed successfully.

**Pull request merged**
