### PR TITLE
[npm] Updating packages to fix Mac build

### PR DESCRIPTION
**Pull request by brianjjones**
Signed-off-by: Brian Jones <brian.j.jones@intel.com>

### CODE REVIEW

**Comment by xiaoyu3x** [comment]
@brianjjones 
I just used this PR to npm install on Mac, but I got a error.
screen shot 2017-12-07 at 4 47 42 pm

Is there any other steps needed before `npm install`?

**Comment by brianjjones** [comment]
No it should work after npm install.  Strange as it passed Travis.  Was this a fresh clone or merged with an existing fork?  Perhaps a npm cache clean will help if it isn't a fresh merge.  I'll also see if it works for @jimmy-huang.

**Comment by xiaoyu3x** [comment]
hi, @brianjjones
Your PR is OK.
I just 'npm install' again and it is successful

**Comment by brianjjones** [comment]
@nagineni Thanks for the heads up, I'll see about adding those updates as well.

**Pull request merged**
